"Resource/UI/MutationCoopFlyout.res"
{
	"PnlBackground"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"180" [$ENGLISH]
		"wide"					"270" [!$ENGLISH]
		"tall"					"305"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"		"1"
		"paintborder"			"1"
	}

	"BtnMutation2"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation2"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnCommunity5"
		"navDown"				"BtnMutation3"
		"labelText"				"#L4D360UI_Mode_mutation2"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation2"
	}

	"BtnMutation3"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation3"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation2"
		"navDown"				"BtnMutation4"
		"labelText"				"#L4D360UI_Mode_mutation3"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation3"
	}

	"BtnMutation4"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation4"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation3"
		"navDown"				"BtnMutation5"
		"labelText"				"#L4D360UI_Mode_mutation4"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation4"
	}

	"BtnMutation5"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation5"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation4"
		"navDown"				"BtnMutation7"
		"labelText"				"#L4D360UI_Mode_mutation5"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation5"
	}

	"BtnMutation7"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation7"
		"xpos"					"0"
		"ypos"					"80"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation5"
		"navDown"				"BtnMutation8"
		"labelText"				"#L4D360UI_Mode_mutation7"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation7"
	}

	"BtnMutation8"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation8"
		"xpos"					"0"
		"ypos"					"100"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation7"
		"navDown"				"BtnMutation9"
		"labelText"				"#L4D360UI_Mode_mutation8"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation8"
	}

	"BtnMutation9"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation9"
		"xpos"					"0"
		"ypos"					"120"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation8"
		"navDown"				"BtnMutation10"
		"labelText"				"#L4D360UI_Mode_mutation9"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation9"
	}

	"BtnMutation10"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation10"
		"xpos"					"0"
		"ypos"					"140"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation9"
		"navDown"				"BtnMutation14"
		"labelText"				"#L4D360UI_Mode_mutation10"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation10"
	}

	"BtnMutation14"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation14"
		"xpos"					"0"
		"ypos"					"160"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation10"
		"navDown"				"BtnMutation16"
		"labelText"				"#L4D360UI_Mode_mutation14"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation14"
	}

	"BtnMutation16"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation16"
		"xpos"					"0"
		"ypos"					"180"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation14"
		"navDown"				"BtnMutation20"
		"labelText"				"#L4D360UI_Mode_mutation16"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation16"
	}

	"BtnMutation20"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation20"
		"xpos"					"0"
		"ypos"					"200"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation16"
		"navDown"				"BtnCommunity1"
		"labelText"				"#L4D360UI_Mode_mutation20"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation20"
	}

	"BtnCommunity1"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnCommunity1"
		"xpos"					"0"
		"ypos"					"220"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation20"
		"navDown"				"BtnCommunity2"
		"labelText"				"#L4D360UI_Mode_community1"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_community1"
	}

	"BtnCommunity2"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnCommunity2"
		"xpos"					"0"
		"ypos"					"240"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnCommunity1"
		"navDown"				"BtnCommunity4"
		"labelText"				"#L4D360UI_Mode_community2"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_community2"
	}

	"BtnCommunity4"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnCommunity4"
		"xpos"					"0"
		"ypos"					"260"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnCommunity2"
		"navDown"				"BtnCommunity5"
		"labelText"				"#L4D360UI_Mode_community4"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_community4"
	}

	"BtnCommunity5"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnCommunity5"
		"xpos"					"0"
		"ypos"					"280"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnCommunity4"
		"navDown"				"BtnMutation2"
		"labelText"				"#L4D360UI_Mode_community5"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_community5"
	}
}