"Resource/UI/MutationVersusFlyout.res"
{
	"PnlBackground"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"180" [$ENGLISH]
		"wide"					"270" [!$ENGLISH]
		"tall"					"145"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"		"1"
		"paintborder"			"1"
	}

	"BtnMutation11"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation11"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnCommunity6"
		"navDown"				"BtnMutation13"
		"labelText"				"#L4D360UI_Mode_mutation11"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation11"
	}

	"BtnMutation13"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation13"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation11"
		"navDown"				"BtnMutation15"
		"labelText"				"#L4D360UI_Mode_mutation13"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation13"
	}

	"BtnMutation15"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation15"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation13"
		"navDown"				"BtnMutation18"
		"labelText"				"#L4D360UI_Mode_mutation15"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation15"
	}

	"BtnMutation18"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation18"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation15"
		"navDown"				"BtnMutation19"
		"labelText"				"#L4D360UI_Mode_mutation18"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation18"
	}

	"BtnMutation19"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutation19"
		"xpos"					"0"
		"ypos"					"80"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation18"
		"navDown"				"Btncommunity3"
		"labelText"				"#L4D360UI_Mode_mutation19"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_mutation19"
	}

	"BtnCommunity3"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnCommunity3"
		"xpos"					"0"
		"ypos"					"100"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutation19"
		"navDown"				"BtnCommunity6"
		"labelText"				"#L4D360UI_Mode_community3"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_community3"
	}

	"BtnCommunity6"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnCommunity6"
		"xpos"					"0"
		"ypos"					"120"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnCommunity3"
		"navDown"				"BtnMutation11"
		"labelText"				"#L4D360UI_Mode_community6"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"ChangeMutation_community6"
	}
}