"Resource/UI/MutationCategoriesFlyout.res"
{
	"PnlBackground"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"180" [$ENGLISH]
		"wide"					"270" [!$ENGLISH]
		"tall"					"65"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"		"1"
		"paintborder"			"1"
	}

	"BtnMutationSolo"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutationSolo"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutationVersus"
		"navDown"				"BtnMutationCoop"
		"labelText"				"#L4D360UI_Modes_OnePlayer"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"FlmMutationSolo"
	}

	"BtnMutationCoop"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutationCoop"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutationSolo"
		"navDown"				"BtnMutationVersus"
		"labelText"				"#L4D360UI_Modes_FourPlayers"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"FlmMutationCoop"
	}

	"BtnMutationVersus"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMutationVersus"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMutationCoop"
		"navDown"				"BtnMutationSolo"
		"labelText"				"#L4D360UI_Modes_EightPlayers"
		"tooltiptext"			""
		"disabled_tooltiptext"	""
		"style"					"FlyoutMenuButton"
		"command"				"FlmMutationVersus"
	}
}